### ISSUE TITLE
Rewrite for use go regex

### ISSUE THREAD

**Issue by jollheef** [jollheef/appvm#9]
https://github.com/jollheef/appvm/blob/959e6e6596e0d7f74f563a626b5e18634d156012/appvm.go#L210

**Comment by 0sc** [comment]
Hi @jollheef, I'm looking to pick this up. Is there some form I test I could run to ensure the change will work as expected?

**Comment by jollheef** [comment]
Hello.

Just run any application. If it works – all right.

I use Gentoo, but also it was tested on Ubuntu and must work on every GNU/Linux distribution. If you don't use GNU/Linux as main OS – just use any hypervisor with support of nested hardware virtualisation.

Thank you for participating.

**Comment by disc** [comment]
I will take it
